apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: helloenv-prod
resources:
- namespace.yaml
- ../app
- service.yaml
- ingress.yaml
images:
- name: docker.io/sudhanshu456/helloenv
  newName: docker.io/sudhanshu456/helloenv # {"$imagepolicy": "flux-system:helloenv-prod:name"}
  newTag: 1.0.2 # {"$imagepolicy": "flux-system:helloenv-prod:tag"}
patches:
- patch: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: helloenv
    spec:
      template:
        spec:
          containers:
            - name: helloenv
              env:
                - name: ENV
                  value: "prod"
