name: CI
on:
  push:
    branches:
      - main
    tags:
      - 1.*
    paths: ["app/**", ".github/workflows/ci.yaml"]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Tag
        id: check-tag
        run: |
           if [[ ${{ github.event.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               echo "::set-output name=IMAGE_ID::${{ github.ref_name }}"
           else
             ts=$(date +%s)
             branch=${GITHUB_REF##*/}
             echo "::set-output name=IMAGE_ID::${branch}-${GITHUB_SHA::8}-${ts}"
           fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and publish container image
        uses: docker/build-push-action@v4
        with:
          push: true
          context: app
          build-args: VERSION=${{  steps.check-tag.outputs.IMAGE_ID }}
          file: ./app/Dockerfile
          tags: |
            shapai/helloenv:${{  steps.check-tag.outputs.IMAGE_ID }}
